# Site Info
title:              "Bending bits..."
name:               "Bending bits..." 
description:        "Bytes and Words..."
#google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-54128414-2 # Put your Google Analytics code

# Author Info
author_name:        "Mihai Seba" # Your name here
author_email:       ardeleanasm@gmail.com # Your email here
author_gravatar:    0afb9a47eb6654437c6986283cff151c # Your Gravatar md5 hash here for logo
twitter_username:   mihaiseba # Your Twitter username here
github_username:    ardeleanasm # Your GitHub username here
stackoverflow_username: users/1462225/23ars

# Includes an icon in the footer for each username you enter
social:
  - title: twitter
    url: https://twitter.com/mihaiseba
  - title: github
    url: https://github.com/ardeleanasm
  - title: linkedin
    url: https://linkedin.com/in/ardelean-sebastian-mihai

disqus: 23ars
# Site Settings
url: http://ardeleanasm.github.io
paginate: 3
paginate_path: "blog/page:num/"
pages: ./_static_pages
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
permalink: /:title/
baseurl: ""
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
theme:              minima
kramdown:
    input:          GFM
    auto_ids:      true
    entity_output: as_char
    toc_levels:    1..6
    smart_quotes:  lsquo,rsquo,ldquo,rdquo
    hard_wrap:     false
    footnote_nr:   1
    show_warnings: false
    math_engine:   mathjax
sass:
    style:          :compressed



# Other Params
version: v3.7.3
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:			
  - jekyll-paginate #used for pagination
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-github-metadata


defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
